### ISSUE TITLE
Encoding algorithm uses incorrect values

### ISSUE THREAD

**Issue by Herohtar** [whisperfish/blurhash-rs#1]
The AC values range from -1.0 to 1.0, and when computing `actual_maximum_value`, the original implementation takes the absolute value:
https://github.com/woltapp/blurhash/blob/f41a23cc50fba7af5650920d3e7ed4315a21d4c3/Swift/BlurHashEncode.swift#L57

However, this implementation does not use the absolute value:
https://github.com/Raincal/blurhash-rs/blob/ef38509dda21e52a38e5e37636377d8aed753edd/src/lib.rs#L58-L62

This results in a different blurhash than expected.

**Comment by ardyfeb** [comment]
Can you please provide correct example ?

**Comment by rubdos** [comment]
Would be fixed through d3b0132 :)
