### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by zecakeh** [whisperfish/blurhash-rs#4]
It seems there have been a few fixes to this project at the beginning of this year, I was wondering if you're planning to make a new release soon.

I was also wondering if this supports WASM?

**Comment by meh** [comment]
Yeah, I'd really need a new release with #2 merged :panda_face:

**Comment by rubdos** [comment]
@Raincal: @schmiddi, @gferon and I are using blurhash in context of Whisperfish (a third-party Signal client). If you're not interested in maintaining this crate any more, we'd be happy to take this on, for instance by moving it to github.com/whisperfish.  We've done this recently for `rust-phonenumber` as well (as @meh is aware, small world!)

**Comment by Raincal** [comment]
> @Raincal: @Schmiddi, @direc85, @gferon and I are using blurhash in context of Whisperfish (a third-party Signal client). If you're not interested in maintaining this crate any more, we'd be happy to take this on, for instance by moving it to github.com/whisperfish. We've done this recently for `rust-phonenumber` as well (as @meh is aware, small world!)

Thank you for your suggestions. It's been a while since I last wrote Rust. If you're willing to take over this project, I'd be glad to transfer it to your organization.

**Comment by rubdos** [comment]
I have accepted the transfer request here and on crates.io. Thank you!

**Comment by rubdos** [comment]
0.2.0 is out, including an additional vulnerability fix (https://github.com/whisperfish/blurhash-rs/security/advisories/GHSA-cxvp-82cq-57h2)

**Comment by rubdos** [comment]
> I was also wondering if this supports WASM?

I don't see an immediate reason why it wouldn't be rather simple to get it compatible, so patches (including CI!) are welcome!
