### ISSUE TITLE
Incorrect encoding results

### ISSUE THREAD

**Issue by rubdos** [whisperfish/blurhash-rs#8]
When cross-checking with https://blurha.sh/, we seem to encode to the wrong values.

```rust
#[test]
fn test_jelly_beans() {
    use image::{EncodableLayout, GenericImageView};

    let img = image::open("data/octocat.png").unwrap();
    let (width, height) = img.dimensions();
    let blurhash = encode(4, 3, width, height, img.to_rgba8().as_bytes()).unwrap();

    // assert_eq!(blurhash, "LFL4=pI8%foujXofRkWC.loyH?V{");
    assert_eq!(blurhash, "LNAdAqj[00aymkj[TKay9}ay-Sj[");
}
```

The actual result according to blurha.sh is the former assertion, but we encode to the latter. Undoing d3b013245410d3c86024391d53211c8b1ab90888 gives yet another result (`"LBAdAqof00WCqZj[PDay0.WB}pof"`), and 1b07c4a does not seem to have changed the behaviour.

**Comment by Schmiddiii** [comment]
Note that the blurha.sh seems very weird when uploading transparent videos

To reproduce, select one of the four given images on the blurhash website. Then upload the (transparent) octocat image. You will notice that their website overlays the selected image with the octocat image, which can also be (somewhat) seen in the blurhash output of the website.

You should instead test with an non-transparent image (e.g. the octocat with white background has blurhash `LsPGjYWB~qt7R4fQbwaypIofnNWB`, while `blurhash-rs` returns `LsPQ88WB~qt7R4fQbwayo~ofnNWB` (which is still incorrect, but not as incorrect as the value `LFL4=pI8%foujXofRkWC.loyH?V{` you claimed.

**Comment by Schmiddiii** [comment]
And the [python version](https://github.com/halcy/blurhash-python) seems to produce yet another blurhash for the same image: `LsPQ87WB~qt7R4fQbwayo~ofnNWB` (which is if I understand the algorithm correctly that the most significant bit is left (see [here](https://github.com/woltapp/blurhash/blob/master/Algorithm.md#base-83), this is closer to our implementation than the one of the website. So I would not worry too much about the exact values, as long as it looks correct.

**Comment by rubdos** [comment]
Given the inconsistencies in other applications, we'll not be the first one to actually resolve it. Thanks for figuring that out, @Schmiddiii !
